coverage:
  status:
    project:
      default:
        base: auto
        branches:
        - dev
        - master
        flags:
        - unit
        if_ci_failed: error
        informational: false
        only_pulls: false
        paths:
        - lib
        target: 80%
        ignore:
          - "lib/generated"  # ignore folders and all its contents
          - "lib/firebase_options.dart"
          - "lib/gen"
          - "lib/main.dart"
          - "lib/constants"
          - "lib/route"
